/**
 * Station brand registry.
 *
 * The full 10,469-station dataset is NOT imported here — it would add ~3.7 MB
 * to the client bundle. It is served as a static file (`public/data/stations.json`,
 * generated by `scripts/build-stations-json.mjs`) and fetched at runtime via the
 * `useStations` hook (`src/hooks/useStations.ts`).
 */

/** Canonical brand list — used for filter UIs. Order matches the brand JSON files. */
export const BRAND_LIST: string[] = [
  'Petron',
  'Shell',
  'Caltex',
  'Phoenix',
  'SeaOil',
  'Unioil',
  'Other',
];
